global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]


  - job_name: 'entrance-node'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'nat:9100' ]

  - job_name: 'gitlab-node'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'gitlab:9100' ]

  - job_name: 'monitoring-node'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]

  - job_name: 'wordpress-node'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'wordpress:9100' ]

  - job_name: 'db01-node'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'mysql-master:9100' ]

  - job_name: 'db02-node'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'mysql-slave:9100' ]
