global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - send_resolved: true
    to: 'jjvod1@yandex.ru'
    from: 'jjvod90@yandex.ru'
    hello: 'smtp.yandex.ru'
    smarthost: smtp.yandex.ru:465
    auth_username: 'jjvod90@yandex.ru'
    auth_identity: 'jjvod90@yandex.ru'
    auth_password: 'ocrnsznluymicqjd'
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']